import java.security.*;
import java.io.*;
import java.math.BigInteger; 

public class MD5 { 
	public static String foragivendata(String input) 
	{ 
		try { 
          
			MessageDigest md1 = MessageDigest.getInstance("MD5"); 
			byte[] messageDigest = md1.digest(input.getBytes());  
			BigInteger nos = new BigInteger(1, messageDigest);  
			String hashtxt = nos.toString(16); 
			while (hashtxt.length() < 32) { 
				hashtxt = "0" + hashtxt; 
			} 
			return hashtxt; 
		} 
		catch (NoSuchAlgorithmException e) { 
			throw new RuntimeException(e); 
		} 
	} 
	public static void main(String args[]) throws NoSuchAlgorithmException 
	{ 
	System.out.println("Hashvalues for Practical Cryptography and my full name generated by md5: ");

		String givendata = "Practical Cryptography"; 
		System.out.println("\n" + givendata + " : " + foragivendata(givendata));
		}   
} 